name: 'Auto-PyPI-GitHubPackage-Docker-Release'
description: 'A GitHub Action for releasing Python packages in PyPI and Docker images in Docker Hub and GitHub Docker Packages.'
author: 'Md. Musfiqur Rahaman'

branding:
  icon: 'chevrons-right'
  color: 'white'
  
inputs:
  version:
    description: 'Version number for the release.'
    required: true
  pypi_token:
    description: 'PyPI API token'
    required: true
  dockerhub_username:
    description: 'DockerHub username'
    required: true
  dockerhub_password:
    description: 'DockerHub password'
    required: true
  dockerhub_pat:
    description: 'DockerHub Personal Access Token'
    required: true
  docker_image_name:
    description: 'Docker Image Name'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  the_github_username:
    description: 'GitHub username'
    required: true
  the_github_repo_name:
    description: 'GitHub Repository Name'
    required: true
    
outputs:
  version:
    description: 'The version of the release.'
    
runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
      shell: bash

    - name: Get the current version
      id: current-version
      run: echo "version=$(python setup.py --version)" >> $GITHUB_ENV
      shell: bash

    - name: Check commit message
      run: |
        if [[ $(git log -1 --pretty=%B) != "Release v${{ inputs.version }}" ]]; then
          echo "Commit message does not match the release pattern."
          exit 1
        fi
      shell: bash

    - name: Setup PyPI Package using poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry build
        poetry config pypi-token.pypi ${{ inputs.pypi_token }}
        poetry publish
      shell: bash

    - name: Create a new release
      uses: CupOfTea696/gh-action-auto-release@v1.0.2
      with:
        title: "Release ${{ inputs.version }}"
        tag: "v${{ inputs.version }}"
        draft: false
        regex: "/^Release #${{ inputs.version }}$/i"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_pat }}

   - name: Upload to GitHub Packages using Docker
      run: |
        # Echo input variables for debugging
        echo "GitHub Repo Name: ${{ inputs.the_github_repo_name }}"
        echo "Docker Hub Username: ${{ inputs.dockerhub_username }}"
        echo "Docker Image Name: ${{ inputs.docker_image_name }}"
        echo "Version: ${{ inputs.version }}"
        echo "GitHub Username: ${{ inputs.the_github_username }}"
    
        # Building the Docker image
        docker build -t ${{ inputs.the_github_repo_name }} .
    
        # Login to Docker Hub
        # echo ${{ inputs.dockerhub_pat }} | docker login -u ${{ inputs.dockerhub_username }} --password-stdin
    
        # Login to GitHub Container Registry
        echo ${{ inputs.github_token }} | docker login ghcr.io -u ${{ inputs.the_github_username }} --password-stdin
    
        # Tag the image for Docker Hub
        docker tag ${{ inputs.the_github_repo_name }} ${{ inputs.dockerhub_username }}/${{ inputs.docker_image_name }}:v${{ inputs.version }}
    
        # Tag the image for GitHub Container Registry
        docker tag ${{ inputs.the_github_repo_name }} ghcr.io/${{ inputs.the_github_username }}/${{ inputs.docker_image_name }}:v${{ inputs.version }}
    
        # Push the image to Docker Hub
        docker push ${{ inputs.dockerhub_username }}/${{ inputs.docker_image_name }}:v${{ inputs.version }}
    
        # Push the image to GitHub Container Registry
        docker push ghcr.io/${{ inputs.the_github_username }}/${{ inputs.docker_image_name }}:v${{ inputs.version }}
      shell: bash

